---
title: "new class enrollment"
author: "Chase Souder"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(googlesheets4)
library(fs)
library(readxl)
library(janitor)
```

```{r, include = FALSE}
download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx", "spring_enrollment_2020.xlsx")

download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx", "old_spring_enrollment.xlsx")
```

```{r, include = FALSE}
spring_2020 <- read_excel("2020_spring_enrollment.xlsx",
                          skip = 3) %>%
  clean_names() %>%
  filter(!is.na(course_name))

spring_2019 <- read_excel("2019_spring_enrollment.xlsx",
                          skip = 3) %>%
  clean_names() %>%
  filter(!is.na(course_name)) %>%
  select(course_id)

new_classes <- spring_2020 %>%
  anti_join(spring_2019, by = "course_id") %>%
  arrange(desc(total)) %>%
  slice(1:5) %>%
  pull(course_name)
  
```

The 5 largest new classes are `r new_classes`.